"""Export SDL syntax tables from compiled HTML to C++ decoder skeletons.

The mirror operation of ``--codesync``: where ``--codesync`` checks that
C++ ``READ_*`` macros agree with the spec, this module *generates* a
C++ skeleton from the spec.  Useful when starting a new reference codec
implementation from a finalized spec text.

Pipeline:

1. Walk the compiled HTML for every ``<table class="sdl-syntax-table">``.
2. For each table, derive a function name from the caption (or the
   nearest enclosing heading ID).
3. Emit one ``<function>.h`` per syntax function with stub macros
   (``READ_FLAG``, ``READ_CODE``, etc.) chosen by descriptor.
4. Emit a ``decoder_stubs.cpp`` with empty function bodies that include
   each header.

Macros are conservative: only descriptors with a matching macro name are
emitted; the rest become a ``// TODO:`` comment so authors can fill them
in by hand.
"""

from __future__ import annotations

import logging
import re
from pathlib import Path
from typing import TYPE_CHECKING

from specbuild.checks.codesync import SyntaxField, extract_sdl_tables

if TYPE_CHECKING:
    from bs4 import BeautifulSoup


# Map SDL descriptor name -> (macro_name, takes_width).
# A small, intentionally conservative set: anything else becomes a TODO.
_DESCRIPTOR_TO_MACRO: dict[str, tuple[str, bool]] = {
    "u": ("READ_CODE", True),
    "f": ("READ_FLAG", False),
    "ue": ("READ_UVLC", False),
    "se": ("READ_SVLC", False),
    "uvlc": ("READ_UVLC", False),
    "svlc": ("READ_SVLC", False),
    "leb128": ("READ_LEB128", False),
    "le": ("READ_LE", True),
    "b": ("READ_BYTE", False),
}

_IDENT_RE = re.compile(r"[^A-Za-z0-9_]+")


def _safe_ident(name: str) -> str:
    """Coerce *name* into a safe C++ identifier (alphanumeric + underscore)."""
    cleaned = _IDENT_RE.sub("_", name).strip("_")
    if not cleaned:
        cleaned = "syntax"
    if cleaned[0].isdigit():
        cleaned = f"_{cleaned}"
    return cleaned


def _macro_for(field: SyntaxField) -> tuple[str, str]:
    """Return ``(macro_line, comment)`` for *field*.

    The macro line is C++ source text; the comment may be empty.
    """
    desc = field.descriptor.strip()
    m = re.match(r"([A-Za-z_]\w*)\s*\((.*)\)\s*$", desc)
    name = field.name or "value"
    if m:
        head, args = m.group(1), m.group(2).strip()
        info = _DESCRIPTOR_TO_MACRO.get(head)
        if info is not None:
            macro, takes_width = info
            if takes_width:
                width = args or "1"
                return (
                    f'    {macro}({width}, {name}, "{name}");',
                    "",
                )
            return (
                f'    {macro}({name}, "{name}");',
                "",
            )
    # Fallback for keyword-only descriptors / unknowns
    info = _DESCRIPTOR_TO_MACRO.get(desc)
    if info is not None:
        macro, _ = info
        return (
            f'    {macro}({name}, "{name}");',
            "",
        )
    return (
        f"    // TODO: {desc} {name};",
        f"unrecognized descriptor: {desc}",
    )


_HEADER_PROLOGUE = """\
// Auto-generated by specbuild --export-sdl. Do not edit by hand.
// Each macro corresponds to a syntax-element row from the spec.
#pragma once

namespace specbuild_decoder {
"""

_HEADER_EPILOGUE = """\
}  // namespace specbuild_decoder
"""


def _render_header(function: str, fields: list[SyntaxField]) -> str:
    """Render a per-function ``.h`` skeleton string."""
    fn = _safe_ident(function)
    lines: list[str] = [_HEADER_PROLOGUE.strip(), ""]
    lines.append(f"// Function: {function}")
    lines.append(f"inline void parse_{fn}() {{")
    if not fields:
        lines.append("    // (no fields parsed from spec table)")
    for f in fields:
        macro_line, comment = _macro_for(f)
        if comment:
            lines.append(f"    // [{comment}]")
        cond = (f.condition or "").strip()
        if cond:
            lines.append(f"    if ({cond}) {{")
            lines.append(f"    {macro_line}")
            lines.append("    }")
        else:
            lines.append(macro_line)
    lines.append("}")
    lines.append("")
    lines.append(_HEADER_EPILOGUE.strip())
    return "\n".join(lines) + "\n"


_DECODER_PROLOGUE = """\
// Auto-generated by specbuild --export-sdl. Do not edit by hand.
// One stub function body per syntax function in the spec.
"""


def _render_decoder_stubs(functions: list[str], header_dir_name: str) -> str:
    lines: list[str] = [_DECODER_PROLOGUE.strip(), ""]
    for fn_raw in functions:
        fn = _safe_ident(fn_raw)
        lines.append(f'#include "{header_dir_name}/{fn}.h"')
    lines.append("")
    lines.append("namespace specbuild_decoder {")
    for fn_raw in functions:
        fn = _safe_ident(fn_raw)
        lines.append("")
        lines.append(f"void decode_{fn}() {{")
        lines.append(f"    parse_{fn}();")
        lines.append("    // TODO: implement decoder side effects")
        lines.append("}")
    lines.append("")
    lines.append("}  // namespace specbuild_decoder")
    return "\n".join(lines) + "\n"


def export_sdl(
    soup_or_path: BeautifulSoup | Path,
    output_dir: Path,
) -> dict[str, Path]:
    """Walk SDL tables in *soup_or_path* and emit C++ skeletons under *output_dir*.

    Returns:
        Mapping ``{function_name: header_path}`` plus the special key
        ``__decoder__`` pointing at ``decoder_stubs.cpp``.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    headers_dir = output_dir / "headers"
    headers_dir.mkdir(parents=True, exist_ok=True)

    tables = extract_sdl_tables(soup_or_path)
    written: dict[str, Path] = {}
    for func_name, fields in tables.items():
        text = _render_header(func_name, fields)
        path = headers_dir / f"{_safe_ident(func_name)}.h"
        path.write_text(text, encoding="utf-8")
        written[func_name] = path
        logging.debug(f"export-sdl: wrote {path.name} ({len(fields)} fields)")

    stubs_text = _render_decoder_stubs(list(tables.keys()), headers_dir.name)
    stubs_path = output_dir / "decoder_stubs.cpp"
    stubs_path.write_text(stubs_text, encoding="utf-8")
    written["__decoder__"] = stubs_path

    logging.info(
        "export-sdl: wrote %d header(s) + decoder_stubs.cpp into %s",
        len(tables),
        output_dir,
    )
    return written


__all__ = ["export_sdl"]
