"""Progressive Web App (PWA) support for offline specification viewing.

Generates the ``manifest.json`` web app manifest, a ``sw.js`` service worker
for offline caching, and injects the required ``<link>`` / ``<meta>`` / ``<script>``
tags into the HTML ``<head>``.

Usage from the build pipeline::

    from specbuild.enhancements.pwa import inject_pwa_soup, generate_pwa_files

    inject_pwa_soup(soup)                          # modify HTML in memory
    generate_pwa_files(target_dir, file_list=[…])  # write manifest + SW
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

from specbuild.config import CONFIG
from specbuild.theme import THEME
from specbuild.utils import inject_js

# Icon specifications: (size_px, filename, manifest "purpose" value).
_ICON_SPECS = [
    (192, "icon-192x192.svg", "any"),
    (512, "icon-512x512.svg", "any maskable"),
]


# ---------------------------------------------------------------------------
# Manifest generation
# ---------------------------------------------------------------------------


def _build_manifest() -> dict:
    """Build the web app manifest dict from config and theme values."""
    return {
        "name": CONFIG.spec_full_name,
        "short_name": CONFIG.spec_name,
        "description": f"{CONFIG.spec_full_name} — offline-capable specification viewer",
        "start_url": "index.html",
        "scope": ".",
        "display": "standalone",
        "orientation": "any",
        "theme_color": THEME.color_accent,
        "background_color": THEME.banner_bg,
        "categories": ["reference", "documentation"],
        "icons": [
            {
                "src": f"images/{name}",
                "sizes": f"{size}x{size}",
                "type": "image/svg+xml",
                "purpose": purpose,
            }
            for size, name, purpose in _ICON_SPECS
        ],
    }


# ---------------------------------------------------------------------------
# Service worker generation
# ---------------------------------------------------------------------------

_SW_TEMPLATE = """\
/* Service Worker — auto-generated by specbuild PWA module.
   Caches all specification assets for offline viewing. */

const CACHE_NAME = '{cache_name}';
const ASSETS = {assets_json};

self.addEventListener('install', function (event) {{
  event.waitUntil(
    caches.open(CACHE_NAME).then(function (cache) {{
      return cache.addAll(ASSETS);
    }})
  );
  self.skipWaiting();
}});

self.addEventListener('activate', function (event) {{
  event.waitUntil(
    caches.keys().then(function (names) {{
      return Promise.all(
        names.filter(function (n) {{ return n !== CACHE_NAME; }})
             .map(function (n) {{ return caches.delete(n); }})
      );
    }})
  );
  self.clients.claim();
}});

self.addEventListener('fetch', function (event) {{
  event.respondWith(
    caches.match(event.request).then(function (cached) {{
      return cached || fetch(event.request);
    }})
  );
}});
"""


def _build_service_worker(cache_name: str, file_list: list[str]) -> str:
    """Render the service worker JS with the given cache name and file list."""
    # '.' caches the directory root; index.html and manifest.json are
    # already discovered by _collect_output_files but listed explicitly
    # as a safety net.
    assets = sorted(set(["."] + file_list))
    return _SW_TEMPLATE.format(
        cache_name=cache_name,
        assets_json=json.dumps(assets, indent=2),
    )


# ---------------------------------------------------------------------------
# Icon generation (simple SVG placeholder)
# ---------------------------------------------------------------------------

_ICON_SVG = """\
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {size} {size}">
  <rect width="{size}" height="{size}" rx="24" fill="{color}"/>
  <text x="50%" y="54%" dominant-baseline="middle" text-anchor="middle"
        font-family="Arial, sans-serif" font-weight="bold"
        font-size="{font_size}" fill="white">{text}</text>
</svg>
"""


def _generate_icon(size: int, text: str, color: str) -> str:
    """Generate a simple SVG icon with centered text."""
    font_size = size // 3
    return _ICON_SVG.format(size=size, color=color, font_size=font_size, text=text)


# ---------------------------------------------------------------------------
# HTML injection
# ---------------------------------------------------------------------------


def inject_pwa_soup(soup: Any) -> None:
    """Inject PWA ``<link>``, ``<meta>``, and service-worker registration into ``<head>``.

    Args:
        soup: BeautifulSoup document (modified in place).
    """
    head = soup.find("head")
    if not head:
        return

    # Manifest link
    manifest_link = soup.new_tag("link", rel="manifest", href="manifest.json")
    head.append(manifest_link)

    # Theme color
    theme_meta = soup.new_tag("meta")
    theme_meta["name"] = "theme-color"
    theme_meta["content"] = THEME.color_accent
    head.append(theme_meta)

    # Apple mobile web app
    apple_capable = soup.new_tag("meta")
    apple_capable["name"] = "apple-mobile-web-app-capable"
    apple_capable["content"] = "yes"
    head.append(apple_capable)

    apple_title = soup.new_tag("meta")
    apple_title["name"] = "apple-mobile-web-app-title"
    apple_title["content"] = CONFIG.spec_full_name
    head.append(apple_title)

    apple_icon = soup.new_tag("link", rel="apple-touch-icon", href=f"images/{_ICON_SPECS[0][1]}")
    head.append(apple_icon)

    # Service worker registration
    inject_js(
        soup,
        "pwa-sw-register",
        "if ('serviceWorker' in navigator) {"
        "  window.addEventListener('load', function() {"
        "    navigator.serviceWorker.register('sw.js')"
        "      .then(function(r) { console.log('SW registered:', r.scope); })"
        "      .catch(function(e) { console.log('SW registration failed:', e); });"
        "  });"
        "}",
    )


# ---------------------------------------------------------------------------
# File generation (call after output dir is finalized)
# ---------------------------------------------------------------------------


def _collect_output_files(target_dir: Path) -> list[str]:
    """Walk *target_dir* and return relative paths suitable for SW caching."""
    files: list[str] = []
    for p in target_dir.rglob("*"):
        if not p.is_file():
            continue
        rel = p.relative_to(target_dir).as_posix()
        # Skip the service worker itself and hidden files
        if rel == "sw.js" or rel.startswith("."):
            continue
        files.append(rel)
    return files


def generate_pwa_files(target_dir: Path, cache_name: str | None = None) -> None:
    """Write ``manifest.json``, ``sw.js``, and placeholder icons to *target_dir*.

    Args:
        target_dir: The output directory containing the built specification.
        cache_name: Cache version string for the service worker.
                    Defaults to the directory name (which includes date + SHA).
    """
    if cache_name is None:
        cache_name = f"spec-{target_dir.name}"

    # 1. Manifest
    manifest = _build_manifest()
    manifest_path = target_dir / "manifest.json"
    manifest_path.write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    logging.info(f"Generated PWA manifest: {manifest_path.name}")

    # 2. Icons (only if not already present)
    images_dir = target_dir / "images"
    images_dir.mkdir(exist_ok=True)

    icon_text = CONFIG.spec_name[:3].upper()
    for size, name, _purpose in _ICON_SPECS:
        icon_path = images_dir / name
        if not icon_path.exists():
            icon_path.write_text(
                _generate_icon(size, icon_text, THEME.color_accent),
                encoding="utf-8",
            )

    # 3. Service worker (must be last — it catalogs all files)
    file_list = _collect_output_files(target_dir)
    sw_js = _build_service_worker(cache_name, file_list)
    sw_path = target_dir / "sw.js"
    sw_path.write_text(sw_js, encoding="utf-8")
    logging.info(f"Generated service worker: {sw_path.name} ({len(file_list)} assets cached)")
