"""Table structure validation: check HTML tables for consistency and accessibility.

Validates that tables in the specification follow best practices:

- Consistent column counts across rows (no ragged rows)
- Proper ``<thead>``/``<tbody>`` structure
- ``scope`` attributes on header cells
- ``<caption>`` or ``aria-label`` for accessibility
- No empty tables
"""

from __future__ import annotations

import logging
from collections import Counter
from pathlib import Path

from specbuild.utils import find_nearest_heading, get_bs4, read_html


def validate_tables(html_path: Path) -> list[dict]:
    """File-based wrapper around :func:`validate_tables_soup`.

    Args:
        html_path: Path to the compiled HTML file.

    Returns:
        List of issue dicts.
    """
    try:
        get_bs4()
    except ImportError:
        logging.warning("BeautifulSoup not available, skipping table validation")
        return []

    logging.info(f"Validating tables in {html_path.name}")
    soup = read_html(html_path)
    return validate_tables_soup(soup)


def validate_tables_soup(soup: object) -> list[dict]:
    """Validate all ``<table>`` elements in the parsed HTML.

    Args:
        soup: BeautifulSoup document (read-only).

    Returns:
        List of issue dicts with ``rule``, ``table_id``, ``detail``,
        ``context`` keys.
    """
    issues: list[dict] = []

    for table in soup.find_all("table"):
        # Skip SDL syntax tables — they are auto-generated by the build
        # system and have a known structure that doesn't follow general
        # HTML table conventions (varying column spans, no captions).
        # Also skip presentational tables (e.g. operator definitions).
        classes = table.get("class", [])
        if "sdl-syntax-table" in classes or "table-nohead" in classes:
            continue

        table_id = table.get("id", "")
        context = find_nearest_heading(table)

        # Check for caption or aria-label
        caption = table.find("caption")
        aria_label = table.get("aria-label", "")
        if not caption and not aria_label:
            issues.append(
                {
                    "rule": "table-no-caption",
                    "table_id": table_id,
                    "detail": "Table has no <caption> or aria-label",
                    "context": context,
                }
            )

        # Check for thead/tbody structure
        thead = table.find("thead")
        tbody = table.find("tbody")
        rows = table.find_all("tr")

        if not rows:
            issues.append(
                {
                    "rule": "table-empty",
                    "table_id": table_id,
                    "detail": "Table has no rows",
                    "context": context,
                }
            )
            continue

        # Single pass over rows: count columns and collect th cells
        col_counts: list[int] = []
        has_th = False
        all_th_cells: list[object] = []

        for row in rows:
            cells = row.find_all(["td", "th"])
            count = 0
            for cell in cells:
                if cell.name == "th":
                    has_th = True
                    all_th_cells.append(cell)
                colspan = cell.get("colspan", "1")
                try:
                    count += int(colspan)
                except (ValueError, TypeError):
                    logging.debug(f"Invalid colspan value {colspan!r}, treating as 1")
                    count += 1
            col_counts.append(count)

        if not thead and not tbody and has_th:
            issues.append(
                {
                    "rule": "table-no-thead",
                    "table_id": table_id,
                    "detail": "Table has <th> cells but no <thead>/<tbody> structure",
                    "context": context,
                }
            )

        # Check consistent column counts
        if col_counts:
            expected = Counter(col_counts).most_common(1)[0][0]
            for i, count in enumerate(col_counts):
                if count != expected and count > 0:
                    issues.append(
                        {
                            "rule": "table-ragged-row",
                            "table_id": table_id,
                            "detail": f"Row {i + 1} has {count} columns, expected {expected}",
                            "context": context,
                        }
                    )

        # Check scope attributes on th cells (already collected above)
        for th in all_th_cells:
            if not th.get("scope"):
                issues.append(
                    {
                        "rule": "th-no-scope",
                        "table_id": table_id,
                        "detail": f"<th> without scope: {th.get_text(strip=True)[:40]}",
                        "context": context,
                    }
                )

    return issues


def report_table_validation(
    issues: list[dict],
    *,
    strict: bool = False,
) -> None:
    """Log table validation findings.

    Args:
        issues: List from :func:`validate_tables`.
        strict: If True, exit with error when issues are found.
    """
    if not issues:
        logging.info("Table validation passed: all tables are well-formed")
        return

    logging.warning(f"Table validation: {len(issues)} issue(s)")
    for issue in issues:
        logging.warning(f"  [{issue['rule']}] {issue['detail']} (near: {issue['context']})")

    if strict:
        raise SystemExit(1)
